//
// Created by jaume on 4/12/21.
//

#ifndef KARATESPARRING_INCLUDE_CONFIG_DISPLAYCONFIG_H_
#define KARATESPARRING_INCLUDE_CONFIG_DISPLAYCONFIG_H_

#define DISPLAY_WIDTH           128
#define DISPLAY_BARS            32
#define DISPLAY_HEIGHT          32

#endif //KARATESPARRING_INCLUDE_CONFIG_DISPLAYCONFIG_H_