//
// Created by jaume on 3/25/21.
//

#ifndef KARATESPARRING_INCLUDE_IMPACT_IMPACTCONFIG_H_
#define KARATESPARRING_INCLUDE_IMPACT_IMPACTCONFIG_H_

#define PEAK_VALUES_LENGTH    32
#define PEAK_RANGE_DISTANCE   1

#endif //KARATESPARRING_INCLUDE_IMPACT_IMPACTCONFIG_H_